### ISSUE TITLE
release date

### ISSUE THREAD

**Issue by toyot-li** [IDEA-Research/3D-deformable-attention#1]
@LHY-HongyangLi @rentainhe Hi, thanks for your great work. May I know the expected code release schedule?

**Comment by LHY-HongyangLi** [comment]
Thank you for your interest in our work. We do have a plan to release the code, probably in 1-2 weeks or even earlier. Please stay tuned or check with us after a few weeks.

**Comment by toyot-li** [comment]
@LHY-HongyangLi Thanks for your timely reply. Look forward to the release in the near future!

**Comment by LHY-HongyangLi** [comment]
The code has been released, I'll close this issue.

**Comment by toyot-li** [comment]
@LHY-HongyangLi Nice job. I have another question when reviewing the released code. The depth head is a `DepthHead_MLVGDpt` by default. How much performance difference if the more common `DepthHead` is used here?

**Comment by LHY-HongyangLi** [comment]
According to our experiments, it seems has little effect on the final performance. We use “Multiple Level Ground Truth” for the learning of depth at the very beginning of this work since we thought the further the harder to predict a precise depth. And, this is a very general operation in monocular depth estimation area.

You can try to improve the quality of predicted depth distribution by following the recent progress of monocular depth estimation or even the stereo-based methods (SOLOFusion for example). Believing that with the help of better depth distribution, DFA3D can provide you a higher performance improvement.

**Comment by toyot-li** [comment]
@LHY-HongyangLi Thanks for the clarification. I find that the data pipeline loads offline depth maps, but the provided link in the README seems wrong (actually a pth ckpt).

**Comment by LHY-HongyangLi** [comment]
Thanks for your reminding very much! And I have updated the link.
